title: Loptis的博客
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 改个名字 # add your name
author-img: head.jpeg # add your photo
about-author: 昨夜雨疏风骤，浓睡不消残酒。试问卷帘人，却道海棠依旧。知否，知否？应是绿肥红瘦。 # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: https://github.com/ # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: gaoy0902@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

timezone: Asia/Beijing

encoding: utf-8

#gitment
comment_user: loptis
comment_admin: loptis
comment_repo: Loptis/jekyll-comment
comment_gitalk_clientId: f78e210a3819d342b966
comment_gitalk_clientSecret: 15d367ba840fd5d3d1724e0ae7a227b8a45e1c4a


